#!/usr/bin/env bash
# Render the launcher icon at every size the supported devices ask for, and
# rewrite monkey.jungle so each device points at its exact size.
#
# Launcher icon sizes differ per product; shipping one bitmap makes the compiler
# rescale it (with a warning, and a soft icon). This keeps every device crisp.
#
# Requires rsvg-convert (brew install librsvg).

set -euo pipefail
# shellcheck source=scripts/lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

MASTER="$REPO_ROOT/store-assets/icon.svg"
[ -f "$MASTER" ] || die "Missing vector master: $MASTER"
command -v rsvg-convert >/dev/null 2>&1 || die "rsvg-convert not found (brew install librsvg)"

DEVICES="$(buildable_devices)"
[ -n "$DEVICES" ] || die "No devices installed. See docs/ENVIRONMENT.md."

# Ask each device definition how big its launcher icon is.
SIZES_FILE="$(mktemp)"
trap 'rm -f "$SIZES_FILE"' EXIT
for id in $DEVICES; do
  size="$(python3 -c "
import json,sys
c=json.load(open('$DEVICES_DIR/$id/compiler.json'))
print(c.get('launcherIcon',{}).get('width') or '')" 2>/dev/null || true)"
  [ -n "$size" ] && echo "$size $id" >> "$SIZES_FILE"
done
[ -s "$SIZES_FILE" ] || die "Could not read any launcher icon sizes."

# Render one PNG per distinct size.
rm -rf "$REPO_ROOT"/resources-icon-*
for size in $(awk '{print $1}' "$SIZES_FILE" | sort -n -u); do
  dir="$REPO_ROOT/resources-icon-$size/drawables"
  mkdir -p "$dir"
  rsvg-convert -w "$size" -h "$size" "$MASTER" -o "$dir/launcher_icon.png"
  cat > "$dir/drawables.xml" <<XML
<drawables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://developer.garmin.com/downloads/connect-iq/resources.xsd">
    <!-- ${size}x${size} launcher icon, generated by scripts/make-icons.sh. -->
    <bitmap id="LauncherIcon" filename="launcher_icon.png" />
</drawables>
XML
  ok "resources-icon-$size"
done

# Fallback for any device without an explicit override.
rsvg-convert -w 65 -h 65 "$MASTER" -o "$REPO_ROOT/resources/drawables/launcher_icon.png"

# Store listing icon.
rsvg-convert -w 512 -h 512 "$MASTER" -o "$REPO_ROOT/store-assets/icon.png"

# Rewrite the per-device resourcePath block in monkey.jungle.
SIZES_FILE="$SIZES_FILE" python3 - <<'PY'
import os
by_size = {}
for line in open(os.environ["SIZES_FILE"]):
    size, dev = line.split()
    by_size.setdefault(int(size), []).append(dev)

out = [
    "project.manifest = manifest.xml",
    "",
    "# Domain, engine and UI.",
    "base.sourcePath = source",
    "",
    "# Unit tests live beside the source so the Run No Evil test runner can find",
    "# them. They are annotated (:test) and only enter the binary with 'monkeyc -t',",
    "# so they cost nothing in a normal or release build.",
    "base.sourcePath = source;tests",
    "",
    "# Shared resources: strings, and the fallback launcher icon.",
    "base.resourcePath = resources",
    "",
    "# Launcher icons are a different pixel size on almost every product, and a",
    "# mismatch makes the compiler rescale the bitmap (with a warning) instead of",
    "# using a crisp one. Each device below points at the resource folder holding",
    "# the icon already rendered at its exact size.",
    "#",
    "# GENERATED by scripts/make-icons.sh — re-run it after changing the product",
    "# list in manifest.xml.",
]
for size in sorted(by_size):
    out.append("")
    out.append("# %dx%d" % (size, size))
    for dev in sorted(by_size[size]):
        out.append("%s.resourcePath = $(%s.resourcePath);resources-icon-%d" % (dev, dev, size))
out.append("")
open("monkey.jungle", "w").write("\n".join(out))
print("monkey.jungle rewritten for %d devices across %d sizes"
      % (sum(len(v) for v in by_size.values()), len(by_size)))
PY

ok "Icons regenerated. Rebuild with: make build-all"
